### ISSUE TITLE
Windows support: spawn

### ISSUE THREAD

**Issue by NightRa** [banacorn/agda-mode#33] opened 2016-07-02 23:07 UTC
When using agda-mode on Windows, loading causes the following error:
"spawn <path to agda exec> ENOENT <path to agda exec>"
spawn does not exist on windows.
It should probably use another command to execute agda on windows.

**Comment by banacorn** [comment] 2016-07-03 08:56
I can't seem to reproduce the error, could you provide some more detail:

1. the version of your Windows
2. the version of agda-mode
3. some fields of the settings of agda-mode:
  1. Agda execution path
  2. Agda program arguments
  3. Automatically search for executable path
  4. Agda program name
4. and copy what it shows in the console (right-click on the editor > inspect element > console )

Thanks.

**Comment by banacorn** [comment] 2016-07-03 08:56
```
spawn ENOENT
```

This is really weird because `spawn` appears to be executed as a command, but it was actually invoked from the node.js API ([child_process.spawn(command[, args][, options])](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)), which should be available on all platforms.

**Comment by banacorn** [comment] 2016-09-03 16:05
Battle hardened in [FLOLAC16](flolac.iis.sinica.edu.tw/flolac16/), looks fine on all machines including Windows, closing this issue.

**Closed by banacorn** 2016-09-03 16:05 UTC
