### ISSUE TITLE
Failed to load the agda-mode package

### ISSUE THREAD

**Issue by vramana** [banacorn/agda-mode#9] opened 2015-03-10 13:25 UTC
**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [agda-mode](https://github.com/banacorn/agda-mode) package, v0.2.12

### Stack Trace

Failed to load the agda-mode package

```
At Cannot find module 'Q'

Error: Cannot find module 'Q'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/vramana/.atom/packages/agda-mode/lib/core.coffee:8:7)
    at Object.<anonymous> (/home/vramana/.atom/packages/agda-mode/lib/core.coffee:216:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/opt/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "metrics",
      "language-agda",
      "jshint",
      "linter-jsxhint",
      "racer",
      "covalent",
      "linter-rust",
      "firepad"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
agda-mode, v0.2.12
atom-pair, v0.37.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-jshint, v0.1.0
pretty-json, v0.3.2
script, v2.18.0

# Dev
No dev packages
```

**Comment by banacorn** [comment] 2015-03-11 07:29
Please try to reinstall `agda-mode`, as `Q` is already in the dependencies, thanks!

**Comment by vramana** [comment] 2015-03-11 23:53
I tried reinstalling `agda-mode` But it doesn't have any effect I am still getting the same error. :frowning:

**Comment by banacorn** [comment] 2015-03-16 03:19
Please go to the directory of `agda-mode` (you can see where it is located by looking at `Settings > Packages / Agda Mode > View Code`), and run this.

```
apm install
```

Atom's package dependency management is a bit messed up, I bumped into this once, too.
Thank you for reporting this and sorry for any inconvenience ><

**Comment by vramana** [comment] 2015-03-16 08:11
I removed the node_modules and did apm install after that but I am still
getting the same error. Is there any way I can provide more log?

On Mon, Mar 16, 2015 at 8:49 AM, Ting-Yen Lai <notifications@github.com>
wrote:

> Please go to the directory of agda-mode (you can see where it is located
> by looking at Settings > Packages / Agda Mode > View Code), and run this.
>
> apm install
>
> Atom's package dependency management is a bit messed up, I bumped into
> this once, too.
> Thank you for reporting this and sorry for any inconvenience ><
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/banacorn/agda-mode/issues/9#issuecomment-81374595>.
>



-- 
Venkata Ramana K.
Senior Undergraduate,
Indian Institute of Science,
Bangalore, India.

**Comment by banacorn** [comment] 2015-03-21 16:17
I couldn't reproduce your issue. But I've encountered something similar once, and I fixed it by typing some random `apm` commands, and the problem just went away somehow.

I've patched (something else) and bumped a new version, please update the package. 

If that doesn't help, please try this: remove `node_modules` and type `apm rebuild`, and see if it helps ._.

**Comment by vramana** [comment] 2015-03-22 15:43
No luck yet. :disappointed: Can it be an issue with `atom` or `apm` ?

**Comment by banacorn** [comment] 2015-03-24 05:53
Possibly, frankly I have no idea why it would happen :(

**Comment by np** [comment] 2015-04-14 23:14
Same error from a fresh install.

**Comment by banacorn** [comment] 2015-04-15 16:02
Hey guys, I think I've located the embarrassing source of issue. ([Cannot find module Q in build](http://stackoverflow.com/a/23896393/2936281)) 

I've patched it (`v0.2.16`) and tested it on some case sensitive file system. Please reinstall the package and see if it ever pops up again.

**Comment by audreyt** [comment] 2015-04-15 16:48
Thanks @banacorn for the fix! 感謝 :rainbow:

**Comment by np** [comment] 2015-04-16 09:29
Thanks for the fix @banacorn !

**Comment by banacorn** [comment] 2015-04-16 12:09
I'll close it then :p

**Closed by banacorn** 2015-04-16 12:09 UTC
